spring.application.name=sistema-guias-despacho

# --- PUERTO DEL SERVIDOR ---
server.port=8080

# --- BASE DE DATOS (ORACLE CLOUD) ---
spring.datasource.url=jdbc:oracle:thin:@bzb80ilr1f18orsy_high?TNS_ADMIN=./src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Renemaria1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# Se desactiva la consola H2 ya que pasamos a Oracle
spring.h2.console.enabled=false

# --- AZURE AD B2C (IDaaS) ---
# URL del tenant configurado por tu compañera en Azure
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/69f25d70-e9e4-44a7-99e9-ce5112f77ddd/v2.0

# --- AWS S3 ---
# Aqui pondremos el nombre del bucket una vez creado en AWS Academy
aws.s3.bucket-name=sistema-guias-despacho-renemaria-sumativa2
aws.region=us-east-1
# Credenciales temporales falsas para evitar el error de Spring Boot en tu entorno local
cloud.aws.credentials.access-key=llave_falsa_temporal
cloud.aws.credentials.secret-key=clave_falsa_temporal

# ==========================================
# CONFIGURACION DE RABBITMQ Y COLAS
# ==========================================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Nombres de las Colas
app.queue.normal=cola-guias-despacho
app.queue.error=cola-guias-errores