spring.application.name=online-course-bff

# ===============================
# 1. CONEXIÓN A BASE DE DATOS ORACLE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=Renemaria1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 'update' creará las tablas automáticamente si no existen, basado en tus Entidades JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# 2. CONFIGURACIÓN RABBITMQ (Docker Local)
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# 3. AWS S3 (Valores temporales para que no explote)
# ===============================
aws.s3.bucket-name=bucket-temporal
aws.s3.region=us-east-1
aws.accessKeyId=llave-falsa
aws.secretAccessKey=secreto-falso
aws.sessionToken=token-falso

# ===============================
# 4. AZURE AD B2C (Lo llenará María)
# ===============================
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://falso.b2clogin.com/falso/discovery/v2.0/keys?p=falso